import * as React from 'react';
export type CompanyIconName =
  | "AutomobileProperty1Eicher"
  | "AutomobileProperty1KubotaProperty2"
  | "AutomobileProperty1TOYODAGOSEI"
  | "AutomobileProperty1UNOMINDA"
  | "CementUltratech"
  | "ChemicalsProperty1Basf"
  | "ChemicalsProperty1SRF"
  | "ComminfraProperty1Adani"
  | "ComminfraProperty1Chhatrapati"
  | "ComminfraProperty1DLF"
  | "ComminfraProperty1Flipkart"
  | "ComminfraProperty1IDEMIA"
  | "ComminfraProperty1IITBombay"
  | "ComminfraProperty1Icic"
  | "ConsumerGoodsProperty1Cocacola"
  | "ConsumerGoodsProperty1Dabur"
  | "ConsumerGoodsProperty1ITC"
  | "ConsumerGoodsProperty1Marico"
  | "ConsumerGoodsProperty1Mondelez"
  | "ConsumerdurablesAshirvad"
  | "ConsumerdurablesProperty1AbGrasigm"
  | "ConsumerdurablesProperty1Havells"
  | "ConsumerdurablesProperty1Nerolac"
  | "ConsumerdurablesProperty1Supreme"
  | "EnegrgyProperty1Cairn"
  | "EnegrgyProperty1Haldiapetrochemicals"
  | "EnegrgyProperty1IndianOIL"
  | "EnegrgyProperty1JSWEnergy"
  | "EnegrgyProperty1Tatapower"
  | "MetalsProperty1JSW"
  | "MetalsProperty1Tata"
  | "MetalsProperty1Vedanta"
  | "OEMProperty1Idex"
  | "OEMProperty1KSB"
  | "PartnershipAccenture"
  | "PharmaProperty1Mainkind"
  | "PharmaProperty1Zydus"
  | "VectorProperty1FeatureCircle"
  | "VectorProperty1FlowView"
  | "VectorProperty1Lighthouse"
  | "VectorProperty1MultiLevelRing"
  | "VectorProperty1ProcessCircle"
  | "VectorProperty1ProcessView"
  | "VectorProperty1Pyramid"
  | "VectorProperty1SemiCircle"
  | "VectorProperty1SplitFlow"
  | "VectorProperty1StackedBlockTower"
  | "VectorProperty1StaircaseProgression1"
  | "VectorProperty1StaircaseProgression2"
  | "VectorProperty1WorldMap";
export interface CompanyIconProps extends React.SVGProps<SVGSVGElement> {
  name: CompanyIconName;
  size?: number | string;
}
export declare const CompanyIcon: React.FC<CompanyIconProps>;
export default CompanyIcon;
