import * as React from 'react';
export type IconName =
  | "AdminPanelProperty1DeviceTypeDetail"
  | "AdminPanelProperty1Devices"
  | "BruceAIProperty1Default"
  | "BruceAIProperty1Default2"
  | "BruceAIProperty1Default3"
  | "BruceProperty1Black"
  | "BruceProperty1White"
  | "DeepsenseProperty1Black"
  | "DeepsenseProperty1White"
  | "DeviceLiveDataAndTrendProperty11"
  | "DeviceLiveDataAndTrendProperty12"
  | "DeviceLiveDataAndTrendProperty13"
  | "DynamicSLDProperty11"
  | "DynamicSLDProperty12"
  | "FaclonlogoProperty1Black"
  | "FaclonlogoProperty1Blue"
  | "FaclonlogoProperty1White"
  | "FaclonmonoProperty1Black"
  | "FaclonmonoProperty1Blue"
  | "FaclonmonoProperty1White"
  | "ForgeFoundryProperty1Black"
  | "ForgeFoundryProperty1White"
  | "ForgeandfoundryProperty1Black"
  | "ForgeandfoundryProperty1White"
  | "GTProperty110"
  | "GTProperty110A"
  | "IOConnectProperty1Black"
  | "IOConnectProperty1White"
  | "IOLensProperty1DashboardOuput"
  | "IOLensProperty1DashboardOuput2"
  | "IOLensProperty1ProcessOverviewDashboard"
  | "IOLensWidgetProperty1BarChart"
  | "IOLensWidgetProperty1DataCard"
  | "IOLensWidgetProperty1DataTable"
  | "IOSenseProperty1Blue"
  | "IOSenseProperty1White"
  | "MapProperty11"
  | "MapProperty12"
  | "MapProperty13"
  | "STProperty1100"
  | "STProperty1120D"
  | "STProperty1120D2"
  | "STProperty1120WD"
  | "STProperty1120WD2"
  | "STProperty150"
  | "STProperty151"
  | "STProperty152CW"
  | "STProperty152CW2"
  | "STProperty152CW3"
  | "STProperty152L"
  | "STProperty152LEU"
  | "STProperty152LEU2"
  | "STProperty152LR"
  | "STProperty152P"
  | "STProperty152Pulse"
  | "STProperty153"
  | "STProperty154"
  | "STProperty154P"
  | "STProperty156C"
  | "STProperty165"
  | "STProperty192"
  | "STProperty194"
  | "STProperty198M"
  | "STProperty198S"
  | "SectionWiseDashboardProperty11"
  | "SectionWiseDashboardProperty12";
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
